name: A Simple Triangle

options:
  bundleIdPrefix: io.github.marcelbraghetto
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  deploymentTarget:
    macOS: "10.12"

settings:
  CLANG_CXX_LANGUAGE_STANDARD: c++17
  CLANG_CXX_LIBRARY: libc++
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  A Simple Triangle:
    type: application
    platform: macOS
    info:
      path: Generated/Info.plist
    entitlements:
      path: Generated/app.entitlements
    sources:
      - Source
      - path: assets
        type: folder
        buildPhase: resources
      - path: vulkan
        type: folder
        buildPhase: resources
    settings:
      HEADER_SEARCH_PATHS:
        - $(PROJECT_DIR)/../../third-party/SDL/include
        - $(PROJECT_DIR)/../../third-party/glm
        - $(PROJECT_DIR)/../../third-party/tiny-obj-loader
        - $(PROJECT_DIR)/../../third-party/SDL2_image
        - $(PROJECT_DIR)/../../third-party/vulkan-mac/macOS/include
      LIBRARY_SEARCH_PATHS:
        - $(inherited)
        - $(PROJECT_DIR)
        - $(PROJECT_DIR)/Frameworks
    dependencies:
      - framework: Frameworks/SDL2.framework
        embed: true
      - framework: Frameworks/SDL2_image.framework
        embed: true
      - framework: Frameworks/libMoltenVK.dylib
        embed: true
      - framework: Frameworks/libvulkan.1.dylib
        embed: true
      - sdk: OpenGL.framework